services:
  otp-build:
    image: opentripplanner/opentripplanner:latest
    container_name: otp_bordeaux_build
    profiles: ["build"]
    environment:
      - JAVA_OPTIONS=-Xmx3G
    volumes:
      - ./otp-service/otp-data:/var/opentripplanner
    command: ["--build", "--save"]

  otp:
    image: opentripplanner/opentripplanner:latest
    container_name: otp
    environment:
      - JAVA_OPTIONS=-Xmx2G
    volumes:
      - ./otp-service/otp-data:/var/opentripplanner
    ports:
      - "8081:8080"
    command: ["--load", "--serve"]
    restart: unless-stopped